sudo: required
dist: trusty
language: node_js

notifications:
  email: false

node_js: lts/*

cache:
  npm: true

stages:
  - test

jobs:
  include:
    - stage: test
      # Need to force install due to peer deps conflict from @orchestrator/ngx-testing
      install: npm ci --force
      script:
        - npm run format:check
        - npm run build
        - npm run demo-ssr:prerender
        - npm run test:ci
        - npm run test:report
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run release
